### ISSUE TITLE
Is your fork "official" maintained?

### ISSUE THREAD

**Issue by guettli** [jauderho/dive#104]
Your fork looks healthy. Thank you for your work.

Does it make sense to mention your fork in this issue https://github.com/wagoodman/dive/issues/433 ?

If "yes", it might make sense to update parts like this in the README "go get github.com/wagoodman/dive"

**Comment by jauderho** [comment]
It's not "official" per se. I'll keep things updated to the point where it builds with up to date dependencies but do not have cycles for anything more beyond that.

**Comment by joschi** [comment]
https://github.com/wagoodman/dive/issues/553#issuecomment-2461854191

**Comment by jauderho** [comment]
I am happy to move my fork to a new org as a new starting point and co-maintain the deps. Mainly, this just serves as upstream to my Dockerfiles repo: https://github.com/jauderho/dockerfiles
