### ISSUE TITLE
Are there binaries available of this fork?

### ISSUE THREAD

**Issue by voltagex** [jauderho/dive#47]
I don't have a Go build system set up, I don't see where the goreleaser pipeline is running here.

Edit:

In case people need a binary quickly:

```
FROM golang as build-dive
RUN mkdir /src
RUN git clone https://github.com/jauderho/dive/ /src/dive
WORKDIR /src/dive
RUN make build
FROM scratch
COPY --from=build-dive /src/dive/dist/dive_linux_amd64/dive .
```

`DOCKER_BUILDKIT=1 docker build . --output .`

**Comment by jauderho** [comment]
I do not have goreleaser running on this repo at this time. I do have prebuilt Docker images available via here: https://github.com/jauderho/dockerfiles/tree/main/dive
