### ISSUE TITLE
[HELP NEEDED] Migrate dive to use newer gocui code base

### ISSUE THREAD

**Issue by jauderho** [jauderho/dive#88]
dive current still uses the 0.x branch of gocui which is quite old and also the reason why the following is required:

```
// related to https://github.com/awesome-gocui/gocui/blob/master/migrate-to-v1.md
replace github.com/awesome-gocui/gocui => github.com/awesome-gocui/gocui v0.6.0
```

I do not have cycles to work on this at this time but would welcome anyone submitting a pull request.

**Comment by mrc0der** [comment]
Happy to take a look. Love the project and would like to help keep it going.

**Comment by jauderho** [comment]
@wagoodman has fixed this upstream. No longer needed.
